### ISSUE TITLE
Evaluate other lists by elliotwutingfeng

### ISSUE THREAD

**Issue by GiddyGoatGaming** [serverless-dns/blocklists#102]
look into these other lists by elliotwutingfeng (person responsible for inversion list)
-https://raw.githubusercontent.com/elliotwutingfeng/GlobalAntiScamOrg-blocklist/main/global-anti-scam-org-scam-urls-pihole.txt (Global AntiScam Organization)
- https://www.usom.gov.tr/url-list.txt (Computer Emergency Response Team of Turkey)

**Comment by GiddyGoatGaming** [comment]
> Hi @GiddyGoatGaming, thanks for the mention.
> 
> The feed `https://raw.githubusercontent.com/elliotwutingfeng/InternetstiftelsenDomains/main/nu_domains.txt` contains domains found in the zonefile for the island state of Niue. It is not a blocklist.
> 
> For the USOM blocklist, the source (containing both URLs and IPv4 addresses) is `https://www.usom.gov.tr/url-list.txt`. I wrote a scraper for it as I had connectivity issues to USOM from my location.

Great, il update it right now

**Comment by ignoramous** [comment]
Next blocklist build is on 16 Dec. I'll try to eval and incl before that. Exploring possibilities to see if it can replace one of the dead lists (without surprising folks).

**Comment by ignoramous** [comment]
Wu Tingfeng's global anti-scam lists are in as a replacement for a previously dead list: https://github.com/serverless-dns/blocklists/commit/bdfa56214c25cb998f7f51cb5f7686afc5627d5a
