### ISSUE TITLE
Consider adding another list for vaping

### ISSUE THREAD

**Issue by GiddyGoatGaming** [serverless-dns/blocklists#106]
Consider adding 
https://raw.githubusercontent.com/jaykepeters/Blocklists/master/Drugs/vaping.txt

hasn’t been updated in 4 years but has more entries then the one made by the block list project. Might be worth adding

**Comment by ignoramous** [comment]
Yep, it could augment this existing `vaping` list:

https://github.com/serverless-dns/blocklists/blob/cc32900dea28271c84f877d6dcf9a46aae5bba1f/config.json#L1684-L1690

**Comment by ignoramous** [comment]
it had some uniq domains, so included it (despite no updates for 3 years): https://github.com/serverless-dns/blocklists/commit/6f48a2c96bc8219f15f36221c7a335bf19e8147d

The vaping list looks like it is maintained by a teenager...

**Comment by GiddyGoatGaming** [comment]
> it had some uniq domains, so included it (despite no updates for 3 years): [6f48a2c](https://github.com/serverless-dns/blocklists/commit/6f48a2c96bc8219f15f36221c7a335bf19e8147d)
> 
> The vaping list looks like it is maintained by a teenager...

Makes sense🤣
