### ISSUE TITLE
OISD Basic & Extra

### ISSUE THREAD

**Issue by GiddyGoatGaming** [serverless-dns/blocklists#110]
I think OISD basic and extra would be good additions as seperate lists from any other lists on rethinkdns.

https://dblw.oisd.nl/extra/

https://dblw.oisd.nl/basic/

**Comment by ignoramous** [comment]
Basic for Energized Spark / Blu?

**Comment by GiddyGoatGaming** [comment]
> Basic for Energized Spark / Blu?

That would work. Probably spark would be more fitting just because how non aggressive the list is. And extra could replace energized basic if that isn’t replaced yet

**Comment by ignoramous** [comment]
> And extra could replace energized basic if that isn’t replaced yet

Isn't *Extra* an add-on list for *Basic* and *Full*? I don't think it can quite replace Energized Basic (which is essentially a *Lite* version of the Energized lists?)

**Comment by GiddyGoatGaming** [comment]
Yes, extra is an addition to full and basic. I’m wrong though with replacing energized basic with Oisd extra as they serve different purposes. Extra is there to block domains that some people would prefer unblocked and energized basic is just an all rounder. Sorry about that, I forgot how small Oisd extra was

**Comment by ignoramous** [comment]
Basic: https://github.com/serverless-dns/blocklists/commit/f308a21d89871aeff427e98c378d5a4a9354314b

Extra: Pass
