### ISSUE TITLE
Evaluate Cbuijs Accomplist Repo

### ISSUE THREAD

**Issue by GiddyGoatGaming** [serverless-dns/blocklists#118]
Located at https://github.com/cbuijs/accomplist

They’re plenty of lists here and is updated regularly, some have sources attached and some don’t which makes me confused what sources they include and/or how aggressive they are. The Chris folder has some that might be of some use. The cloak list seems like a good list to add possibly. 

Maybe replace the covid lists sources with https://raw.githubusercontent.com/cbuijs/accomplist/master/covid/optimized.black.domain.list . Includes more sources and removes any duplicates

Maybe replace the easylist Dutch with the one that combines easylist Dutch and the adguard Dutch list. https://raw.githubusercontent.com/cbuijs/accomplist/master/dutch/optimized.black.domain.list

**Comment by ignoramous** [comment]
> Maybe replace the easylist Dutch with the one that combines easylist Dutch and the adguard Dutch list. https://raw.githubusercontent.com/cbuijs/accomplist/master/dutch/optimized.black.domain.list

Sounds good.

> Maybe replace the covid lists sources with https://raw.githubusercontent.com/cbuijs/accomplist/master/covid/optimized.black.domain.list .

We can also add this covid list to an *existing* covid list?

> The cloak list seems like a good list to add possibly.

RDNS uncloaks all domains (which is far more aggressive than simply uncloaking ones list in some list like this one)... so, it depends. If RDNS ever switches to **not** uncloaking all domains, may be lists like these would still help *actual* domain cloakers.

**Comment by GiddyGoatGaming** [comment]
There is also easylist French in the compiler repo which could be made as a new list for rethinkdns. 

There is a family safe list which could be made a new list and it seems to include a lot of good sources in it. Could replace adult (mahadi xion)?

**Comment by ignoramous** [comment]
> Could replace adult (mahadi xion)? this family safe list is bigger in entries though

It could, if it doesn't aggressively block websites with potentially soft-porn / voyeur content like instagram (like some lists do).

> There is a family safe list 

What's in this list? There's *Child Protection* RPi list (which is pretty extensive with some 800K entries). May be it could agument that?

> There is also easylist French in the compiler repo...

Is the underlying EasyList maintained? How large is the list? I ask because, these EasyLists usually lend themselves poorly to domain-based blocking as they're more targeted towards in-browser content-blockers...

**Comment by GiddyGoatGaming** [comment]
> Is the underlying EasyList maintained? How large is the list?

it is maintained by cbuijs but sourced from easylist French and adguard French and has like 11k entries. Il look more into it

**Comment by GiddyGoatGaming** [comment]
> What's in this list? There's _Child Protection_ RPi list (which is pretty extensive with some 800K entries). May be it could agument that?

sources are here https://github.com/cbuijs/accomplist/blob/master/family-safe.sources . Seems like it includes lots of adult site blocking, gambling blocking, drug blocking, and violence blocking

**Comment by GiddyGoatGaming** [comment]
> TLDs: [f88589a](https://github.com/serverless-dns/blocklists/commit/f88589abb5b52a39a4c46ee00680c62c8769ba7f)
> 
> Covid: [2ea1ab4](https://github.com/serverless-dns/blocklists/commit/2ea1ab4973eabcb4e8a9bb938277f7fa510351ba)
> 
> Malware: [9932e67](https://github.com/serverless-dns/blocklists/commit/9932e677855bb85683ce0f1696dc2804a0a9e72f)
> 
> DoH, No-Google, Scamware: [a985971](https://github.com/serverless-dns/blocklists/commit/a985971805d19baabd04712230341bd35c20500d)
> 
> Generic privacy blocklist, Quantum blocklist: [7d5dec0](https://github.com/serverless-dns/blocklists/commit/7d5dec0f19f3b95eb1194877a444f91f0b667f86)
> 
> Adult: [00887f5](https://github.com/serverless-dns/blocklists/commit/00887f5bb407021353326605eae564a4a93b5ba5)
> 
> Not bringing-in the easy-list / dutch / french lists for the time being.

Awesome! Thanks!

**Comment by cbuijs** [comment]
> some have sources attached and some don’t

The ones without sources are generally "generated" without any external sources and contain a mix of my own lists and computed ones. The homograph one for example is computed based on commonly used domains (like facebook, instagram, google, etc), and some personal domain-names.

> and/or how aggressive they are

Depends what you mean with "aggressive" but some block more then others, or generate more or less false-positives. Most of these lists I use myself, for the home-network etc, and I do "exclude" or 'fix" entries where needed. The ["whitelist"](https://github.com/cbuijs/accomplist/tree/master/whitelist) one could be used to counter-effect most lists, it include other sources and my own curations.

Besides this, I do add stuff based on feedback that comes from the ["issues"](https://github.com/cbuijs/accomplist/issues), and if fiable I add the suggestions or when not sure I revert back to the maintainer(s) of the source (list) that contain the domain(s) in question if needed.

Just clarification on how things go :-).
