### ISSUE TITLE
Is there any point to still having "no-facebook" list?

### ISSUE THREAD

**Issue by GiddyGoatGaming** [serverless-dns/blocklists#122]
I'm talking about this one https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all

I feel like there is not any point in keeping it if we have the list by the block list project (https://blocklistproject.github.io/Lists/alt-version/facebook-nl.txt).  jmdugan one does not add anything that the other list does. Maybe I am missing something?

**Comment by ignoramous** [comment]
RDNS can't also remove existing lists. It breaks the "blockstamp" (the thing that encodes user-selected blocklists which looks like this: `1:GOj_PwDABAAAQkGBAIA=`) unless we increment the version (`1:` to may be `2:`). Only replace them with an equivalent. Now, it looks like we did add two no-facebook lists... which we cannot undo (without incr the version).

**Comment by GiddyGoatGaming** [comment]
> RDNS can't also remove existing lists. It breaks the "blockstamp" (the thing that encodes user-selected blocklists which looks like this: `1:GOj_PwDABAAAQkGBAIA=`) unless we increment the version (`1:` to may be `2:`). Only replace them with an equivalent. Now, it looks like we did add two no-facebook lists... which we cannot undo (without incr the version).

So we couldn’t for say, change it to a variant of no google?

**Comment by ignoramous** [comment]
> So we couldn’t for say, change it to a variant of no google?

Besides the fact that there's already a no-google list, not really no. It'd break user's expectations (as in, they'd see a no-google list selected while they had originally selected the now removed no-facebook list... if that makes sense).

**Comment by GiddyGoatGaming** [comment]
> > So we couldn’t for say, change it to a variant of no google?
> 
> Besides the fact that there's already a no-google list, not really no. It'd break user's expectations (as in, they'd see a no-google list selected while they had originally selected the now removed no-facebook list... if that makes sense).

Yep! Makes sense👍
