### ISSUE TITLE
Can't access every blogspot sub domain...

### ISSUE THREAD

**Issue by MagicalAlchemist** [serverless-dns/blocklists#137]
When using "DOH VPN PROXY BYPASS" blocklist, i literally can't access every single blogspot page. What's wrong with this blocklist to the point of including blogspot as a bypass firewall internet?

**Comment by hagezi** [comment]
Thanks, will check ...

**Comment by hagezi** [comment]
@MagicalAlchemist 

The domains I found on my bypass list are:

```
new-proxy-sites.blogspot.com
ukvpns.blogspot.ru
```

Should not cause any problems.

Can you provide me with a sample doamin that does not work?

**Comment by hagezi** [comment]
@ignoramous `blogspot.l.googleusercontent.com` is blocked in https://raw.githubusercontent.com/cbuijs/accomplist/master/doh/deugniets.black.list
ping @cbuijs

**Comment by cbuijs** [comment]
Hi Guys, I maintain/generate that list. I updated/fixed it, should update in next 24 hours or so.

**Comment by hagezi** [comment]
Many thanks @cbuijs

**Comment by ignoramous** [comment]
Thanks everyone.

No longer see `blogspot.l.googleusercontent.com` part of cbuijs blocklists in the latest update (24th Jan): https://archive.is/DtJmh

Closing... Feel free to reopen if anyone think this is a mistake.
