### ISSUE TITLE
TikTok's list appears as having 0 entries

### ISSUE THREAD

**Issue by signed-log** [serverless-dns/blocklists#153]
I don't know if I should have opened that here or at rethink-app

[TikTok](https://raw.githubusercontent.com/nextdns/services/main/services/tiktok) is reported in Rethink `0.54a` as having 0 entries

**Comment by ignoramous** [comment]
Fixed: https://github.com/serverless-dns/blocklists/commit/047a5332c9d74ede70ef2e7926c79759999a61d2

`config.json` was missing `format` for the second tiktok list that was added back in jan: https://github.com/serverless-dns/blocklists/commit/2e2ae5808fd9ac3f50a0c6f97bbef22655a46306 My bad.

The test run after the fix shows 96066 entries for `TikTok`: https://archive.is/yxrIJ
