### ISSUE TITLE
Add Xiaomi blocklist to resolver and client

### ISSUE THREAD

**Issue by fraction1** [serverless-dns/blocklists#166]
Hello,

Ty for your work, love rethink, keep it up.
I'm missing a xiaomi blocklist altough,
Is it possible to add this blocklist to the default Rethink DNS implementation of both [the client](https://rethinkfirewall.com/) and [the resolver](https://rethinkdns.com/)

I edited the json config but i don't know how to create a pull request, sorry

[config.json](https://github.com/serverless-dns/blocklists/files/13797316/config.json)

{
      "vname": "Xiaomi blocklist with whitelist",

      "group": "Privacy",
      "subg": "unknownFalleN",

      "format": "domains",
      "url": "https://raw.githubusercontent.com/unknownFalleN/xiaomi-dns-blocklist/master/xiaomi_dns_block_with_whitelist.lst",

      "pack": ["privacy", "recommended"],
      "level": [1, 1]
    }

Blocklist source:
https://raw.githubusercontent.com/unknownFalleN/xiaomi-dns-blocklist/master/xiaomi_dns_block_with_whitelist.lst

Source comes from:
https://github.com/unknownFalleN/xiaomi-dns-blocklist

Thank you very much
Kind regards

**Comment by ignoramous** [comment]
Thanks for the suggestion. This blocklist has existed in Rethink for over 2 years now. Choose "Xiaomi" in the config to enable it.

https://github.com/serverless-dns/blocklists/blob/2b5258d2954f2850734f6ead9ce2f824fcaa8ddb/config.json#L1609-L1618
