### ISSUE TITLE
RPi, AdRules, Fanboy lists are MIA

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/blocklists#168]
Wanted to ask about something but didn't find a issue that already exists regarding my question so i use this one here.

![Rethink3.jpg](https://github.com/celzero/rethink-app/assets/144499593/c827551f-2f34-4ac8-9177-8cf58ecef7c3)

![Rethink2.jpg](https://github.com/celzero/rethink-app/assets/144499593/ad9afcfc-9386-4a68-9dfd-17e036e6af22)

These three show no entries even though when you click on them their website present plenty do you guys know why?

![Rethink.jpg](https://github.com/celzero/rethink-app/assets/144499593/75454667-c78c-4ff8-8a33-82dcbfd11d92)

![Rethink4.jpg](https://github.com/celzero/rethink-app/assets/144499593/a77bf413-a65b-4aac-ba50-75a2d1345479)

And here the fanboy tracking blocklist is not supported anymore + the Adrules China gives back a 404 are you aware of this?

_Originally posted by @LovingNumbers in https://github.com/celzero/rethink-app/issues/1208#issuecomment-1977636097_

**Comment by LovingNumbers** [comment]
Will this be fixed in the next update or later?

**Comment by ignoramous** [comment]
Done. Thanks. These should be fixed in the next *weekly* update (~24th Sep).
