### ISSUE TITLE
Updating blocklists

### ISSUE THREAD

**Issue by kelvinkad** [serverless-dns/blocklists#173]
Please, consider increasing the frequency of updates to the lists used in rethinkdns.com/configure. Most lists are updated daily with important corrections and additions, so it would be important to update this once a day, but if you put it once a week It's already a good thing, since the actual update interval is months, which makes the custom dns almost unusable.

Thanks in advance for your attention.

**Comment by ignoramous** [comment]
We did investigate frequent updates but found it was too expensive
- #19 

Rethink DNS (the resolver) needs to be moved to a different architecture to support frequent updates. We'll start working on it as soon as we ship https://github.com/celzero/rethink-app/issues/946

(closing this issue as the current code makes frequent updates too expensive)
