### ISSUE TITLE
Please add rule

### ISSUE THREAD

**Issue by biange200** [serverless-dns/blocklists#177]
https://flowus.cn/share/f5b48261-8aed-49a2-bdd2-9b75b20f6ba9

https://ghproxy.net/https://raw.githubusercontent.com/qq5460168/666/master/dns.txt

https://github.com/TG-Twilight/AWAvenue-Ads-Rule

http://rssv.cn/adguard/

**Comment by ignoramous** [comment]
> http://rssv.cn/adguard/
> 
> https://github.com/TG-Twilight/AWAvenue-Ads-Rule https://flowus.cn/share/f5b48261-8aed-49a2-bdd2-9b75b20f6ba9
> 
> https://ghproxy.net/https://raw.githubusercontent.com/qq5460168/666/master/dns.txt

From: https://github.com/celzero/rethink-app/issues/1681

**Comment by ignoramous** [comment]
> rssv.cn/adguard

Missing, unfortunately.

> flowus.cn/share/f5b48261-8aed-49a2-bdd2-9b75b20f6ba9

Missing too.

> ghproxy.net/https://raw.githubusercontent.com/qq5460168/666/master/dns.txt

Seems to be a fork? Added the orig: `raw.githubusercontent.com/8680/GOODBYEADS/refs/heads/master/data/rules/dns.txt`.

> github.com/TG-Twilight/AWAvenue-Ads-Rule

Replaces Fanboy #168 

The newly added lists should show up in the next blocklist update (1 Oct 2024). Thanks.
