### ISSUE TITLE
Include Adult (StevenBlock)  and OISD (nsfw)

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/blocklists#18]
A user says,

> Hi, can you add this hosts file to the adult list? It blocks porn + adware + malware. It has more than 26.000 domains porn and updating frequently. Thanks.
> 
> Great app RethinkDNS.
> 
> https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts

And:

I say,

https://dbl.oisd.nl/nsfw/

**Comment by rustforfuture** [comment]
Completely Agree about these.
Both are great. 👍
