### ISSUE TITLE
Separate out s3 upload and radix-trie generation

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/blocklists#3]
Today, `createTrie.js` does both s3 upload and creating the compact, compressed radix-trie from the downloaded blocklists defined in `blocklistConfig.json`.

Split the upload part into its own file (`uploadTrie.js` or `upload.py` and rename `downloadFromBlocklistConfig.py` to `download.py`?) and creation can remain with `createTrie.js` as the name makes it apparent.

**Comment by santhosh-ponnusamy** [comment]
separation of download, build and upload has been done and tested at commit.
https://github.com/serverless-dns/blocklists/commit/81210022176b2dcde613e534f3f1c746cb8c52fc
https://github.com/serverless-dns/blocklists/runs/3171895827
