### ISSUE TITLE
Update readme with some minor details

### ISSUE THREAD

**Issue by shuvashish76** [serverless-dns/blocklists#31]
Please mention following details on README page
1. To double check blocklist that if it already exist in the list before submitting a PR
(few duplicate examples : #13, #26, #30)
2. Details about `"pack": [ ]`

**Comment by ignoramous** [comment]
Yeah, the code changes are still in flux, as is the design. Once we complete the rewrite (we are rewriting parts of three different pieces of RethinkDNS right now, the app, the blocklists, and the resolver), things will start to fall in place. Or so I hope.

Thanks for flagging this. We can and should do better...
