### ISSUE TITLE
Remove "malwaredomains.com" list and replace it with Urlhaus Filterlists

### ISSUE THREAD

**Issue by rustforfuture** [serverless-dns/blocklists#32]
Hello

Malwaredomains.com is dead.

If you want to support a cached version of it, it is your choice.

But to replace its protection, most adblockers including uBo have switched to Urlhaus Filterlists.

https://github.com/uBlockOrigin/uBlock-issues/issues/1116

https://gitlab.com/curben/urlhaus-filter

There also other malware lists to consider in that issue of uBo (i haven't checked that if you already have them ir not but you had not urlhaus so i wanted to suggest it at least)

More links to the matter:

https://github.com/StevenBlack/hosts/issues/1455

https://github.com/notracking/hosts-blocklists/issues/398

https://github.com/AdguardTeam/FiltersRegistry/issues/364

Best wishes.

**Comment by ignoramous** [comment]
This makes sense. Thanks.

Will look into it. We are in the process of a rewrite, and so changes may very well have to wait until that is done.

**Comment by ignoramous** [comment]
Done.
