### ISSUE TITLE
Remove blocklist.cyberthreatcoalition.org

### ISSUE THREAD

**Issue by elliotwutingfeng** [serverless-dns/blocklists#41]
It was discontinued in late 2021. The blocklist link https://blocklist.cyberthreatcoalition.org/vetted/domain.txt is now dead.

**Comment by ignoramous** [comment]
Yep, plenty dead lists, unfortunately. We plan to "hide" dead lists from the UI.

**Comment by ignoramous** [comment]
This list (and several others) has been marked `dead`. Shows up in the UI but that's a fix for the website and the app, not this repo.
