### ISSUE TITLE
No Google blocklist has an incorrect format

### ISSUE THREAD

**Issue by unknowg** [serverless-dns/blocklists#42]
Hello,
No Google in the blocklistConfig.json has an incorrect format. It's current format is "domains" and it should be "wildcard". Making this changes should block Google's subdomains, right? If this is not how does it work then please [add nickspaargaren/no-google/google-domains to the blocklist.](https://github.com/nickspaargaren/no-google/blob/master/google-domains)
Thanks!

**Comment by unknowg** [comment]
@ignoramous

**Comment by ignoramous** [comment]
Thanks. Note: `wilcard` in the `blocklistConfig.json` today has no effect until #9 is implemented. Also, we are thinking if we should treat all lists as wildcards: https://github.com/serverless-dns/blocklists/issues/9#issuecomment-926216581
