### ISSUE TITLE
Blocklist suggestions GoodbyeAds YouTube Adblock

### ISSUE THREAD

**Issue by FiorenMas** [serverless-dns/blocklists#43]
This blocklist won't 100% block ads on youtube but it reduce ads appear about 50%
Repo: https://github.com/jerryn70/GoodbyeAds
Link: https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Extension/GoodbyeAds-YouTube-AdBlock.txt

**Comment by ignoramous** [comment]
Jerryn70's YouTube Extension was last updated 3 months ago. Is the list (even if not updated frequently) any effective?

**Comment by FiorenMas** [comment]
> Jerryn70's YouTube Extension was last updated 3 months ago. Is the list (even if not updated frequently) any effective?

Seem not,  Jerryn70's YouTube Extension is too outdated not so make some video unable to play.
