### ISSUE TITLE
1Hosts (KidSafe)

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/blocklists#51]
Thanks, how about [`1Hosts (KidSafe)`](https://github.com/badmojr/addons_1Hosts)? :upside_down_face:

_Originally posted by @ignoramous in https://github.com/serverless-dns/blocklists/issues/49#issuecomment-1254194328_

**Comment by badmojr** [comment]
I like my names distinct.
**kidSaf** 🙈
