### ISSUE TITLE
请求增加这个规则

### ISSUE THREAD

**Issue by biange200** [serverless-dns/blocklists#56]
https://code.gitlink.org.cn/damengzhu/banad/raw/branch/main/jiekouAD.txt

**Comment by ignoramous** [comment]
Will consider it, thanks.

**Comment by ignoramous** [comment]
Looks like the CatsTeam blocklists are more complete? https://raw.githubusercontent.com/Cats-Team/AdRules/main/hosts.txt This one you shared (damengzhu/banad) is pretty small / shallow in comparison.

**Comment by biange200** [comment]
That's true. I'm sharing just a small part of it.



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月08日 08:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [serverless-dns/blocklists] 请求增加这个规则 (Issue #56) |

Looks like the CatsTeam blocklists are more complete? https://raw.githubusercontent.com/Cats-Team/AdRules/main/hosts.txt This one you shared (damengzhu/banad) is pretty small / shallow in comparison.

**Comment by biange200** [comment]
> Looks like the CatsTeam blocklists are more complete? https://raw.githubusercontent.com/Cats-Team/AdRules/main/hosts.txt This one you shared (damengzhu/banad) is pretty small / shallow in comparison.



But the rdns built-in rule subscription source does not have cats-team

**Comment by ignoramous** [comment]
Adding it in a bit... #55

**Comment by biange200** [comment]
0.53l will then add these rules?



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月08日 11:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [serverless-dns/blocklists] 请求增加这个规则 (Issue #56) |

Adding it in a bit... #55

**Comment by ignoramous** [comment]
Yes the app will have it in the next release `v053l`, while the *server* should have CatsTeam rules by next week.

Commit: https://github.com/serverless-dns/blocklists/commit/721a15c6cc703d728316d320af4b7c0b847b0cfc
