### ISSUE TITLE
Hagezi blocklists

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/blocklists#57]
Pro and pro++? https://github.com/hagezi/dns-blocklists

**Comment by hagezi** [comment]
Thanks for the suggestion to include my blocklists. I recommend the inclusion of the Pro and Pro++.

Greeting, Gerd

**Comment by ignoramous** [comment]
Included multi pro, multi pro++, vpn/doh/proxy bypass, and threat intelligence: https://github.com/serverless-dns/blocklists/commit/721a15c6cc703d728316d320af4b7c0b847b0cfc

Expect it to show up on RethinkDNS (the resolver and the app) in about a week's time.

Thanks for these lists, I am going to use 'em! (:

**Comment by hagezi** [comment]
@ignoramous Thanks for including my block lists, if I can do anything just let me know.

**Comment by ignoramous** [comment]
Six of Hagezi's blocklists are live, visit: https://sky.rethinkdns.com/1:IBqAAAAIGAAAEA== / `1-eaniaaaabamaaaaq.max.rethinkdns.com` (DoT) :)
