### ISSUE TITLE
Unblock instagram/make a whitelist for instagram

### ISSUE THREAD

**Issue by GiddyGoatGaming** [serverless-dns/blocklists#60]
So I’ve noticed that almost any Adblock list blocks instagram. I’ve used the search tool to see what lists includes graph.instagram.com but it seems to be misleading as other lists have been breaking instagram for me. If there is some way/whitelist to unblock specifically instagram and Facebook. That would be awesome for my use case

**Comment by ignoramous** [comment]
Can you pls share your blockstamp? The end of the DoH url that goes `1:<base64>`. If you're using DoT, then its `1-<base32>`.

**Comment by GiddyGoatGaming** [comment]
It seems to now be working as intended now. Not sure what was going on earlier everything seems to be working perfectly with instagram and also Facebook. So not an issue anymore!
