### ISSUE TITLE
Remove Energized Ultimate & Unified for the time being.

### ISSUE THREAD

**Issue by GiddyGoatGaming** [serverless-dns/blocklists#70]
I don’t see the point to having Energized ultimate and energized unified since they have plenty of false positives and rethinkdns doesn’t supplement with a whitelist. Currently, some of the energized lists are conflicting with nextdns’s service and I think the inconsistency of these 2 lists aren’t worth it for a service like rethinkdns which is limited by cloudflare’s limit. Another reason is that there are currently 230 open issues for the energized lists which are seemingly being ignored. Anyways, that’s my suggestion.

**Comment by GiddyGoatGaming** [comment]
This also frees up ~1.5 million rules which can be used by much higher quality blocklists

**Comment by GiddyGoatGaming** [comment]
Also forgot about energized basic and extreme extension. Remove those also for the time being if you do remove the others

**Comment by ignoramous** [comment]
Of late, I've heard Energized has had problems. Blokada even dropped them as their default list 2 years ago.

[8 Energized lists](https://rethinkdns.com/configure?s=energized) in-use today. Perhaps could be replaced with ShadowWhisperer or RPiList. Personally, I use 1Hosts (Pro), StevenBlack, yhosts, and OISD, so I've never quite known problems with Energized in particular.

**Comment by GiddyGoatGaming** [comment]
I would recommend to remove all the energized lists and anyone could find replacements like rpilist and ShadowWhisperer. Cause I also heard blu go list is breaking gaphy(or whatever that one site needed for video is) and just so many complaints on the nextdns forums right now that it just doesn’t seem worth it to have ~15% of your blocklist capacity taken up by these lists

**Comment by GiddyGoatGaming** [comment]
If you do keep energized ultimate and the set of lists they have. It might be worth switching out energized unified for the porn protection one because the unified list is just ultimate+porn protection and that would save a about 500,000 rules

**Comment by ignoramous** [comment]
Makes sense. I'm inclined to keep Blu Go and/or Spark though, and probably replace the rest?

**Comment by GiddyGoatGaming** [comment]
Ok. I can setup a pull request to remove those and add porn-lite if that would help?

**Comment by ignoramous** [comment]
Can't remove those, only either replace them with equivalent list or mark 'em 'dead' (like with 3 other lists).

**Comment by GiddyGoatGaming** [comment]
Ok, i hope I did it right🙏
