### ISSUE TITLE
Attempt to move as many lists from original source to Ultimate Hosts Blocklist

### ISSUE THREAD

**Issue by GiddyGoatGaming** [serverless-dns/blocklists#77]
I was wondering if I can try to move a bunch of lists from their original source to Ultimate Hosts Blocklist. What this does is cuts down on the amount of domains/hosts that are part of the lists by a light amount. An example of what I mean is Wally3k's list has 350 lines of domains in the original domains form and then has 313 lines of domains when cleaning it. I can probably move around 15 lists over and save a few thousand rules hopefully

**Comment by ignoramous** [comment]
I didn't quite get your query? Generally, the positions of the existing lists must not change. The existing lists can either be marked `dead` *or* replaced with its substitute.

**Comment by GiddyGoatGaming** [comment]
Ok, so here’s what I mean. So with the version on ultimate host blocklist which is called clean. They remove domains which are considered inactive. They keep all active domains so it doesn’t actually affect the end user at all. It just cuts down on the blocklist size by a tiny bit. Lists get updated every 24 hours give or take. All that gets changed for rethinkdns is the url of the list. nothing else. I hope that clears things up

**Comment by ignoramous** [comment]
Ah okay. I wonder if UltimateHostsBlacklist stops updating their "clean" mirror, we might end up even worse?

**Comment by GiddyGoatGaming** [comment]
I would assume the only way it stops getting updated is if pyfunceable (the tool used everyday to check everything) goes down or something. I can’t find how long the lists have been around but it looks like a couple years at least

**Comment by ignoramous** [comment]
I'm going to ask the developer of Ultimate Hosts if the intention is to keep it around for the long term. Otherwise, it is always better to fetch from source.

**Comment by GiddyGoatGaming** [comment]
Sounds good👍
