### ISSUE TITLE
Alternative format for small ublock list question

### ISSUE THREAD

**Issue by GiddyGoatGaming** [serverless-dns/blocklists#79]
Does rethinkdns support this format for the small ublock list? If so, then we can reduce the size of the list by about 90%. https://raw.githubusercontent.com/mtxadmin/ublock/master/hosts_blokada.txt

**Comment by ignoramous** [comment]
We convert all lists to wildcard format even when they aren't... ;)

https://github.com/serverless-dns/trie/blob/cbb7af4d1c78fdac2930a1f6766c24ed272b51ba/src/trie.js#L834-L854

But yes, we do support wildcard lists. Ref: Multipro (Hagezi) entry:

https://github.com/serverless-dns/blocklists/blob/722e2d69215e14fbdf1bed305f147bf3a48c7cdf/config.json#L875-L876

**Comment by GiddyGoatGaming** [comment]
Ok. I just haven’t seen any lists that have the format of a host file and a wildcard. What I mean is having 0.0.0.0 and then having a * also. Il make the pull request to change over because this would be incredible if we can reduce the blocklist size from 900k+ down to ~300k (I think it was)

**Comment by ignoramous** [comment]
> I'll make the pull request to change over because this would be incredible if we can reduce the blocklist size from 900k+ down to ~100k (I think it was)

We already reduce these lists the way you'd expect us to. So, adding `wildcard` format (and this one with both `wildcard` and `hosts` format) makes no material difference in the final size of the merged trie (:

**Comment by GiddyGoatGaming** [comment]
> > I'll make the pull request to change over because this would be incredible if we can reduce the blocklist size from 900k+ down to ~100k (I think it was)
> 
> We already reduce these lists the way you'd expect us to. So, adding `wildcard` format (and this one with both `wildcard` and `hosts` format) makes no material difference to the final size of the merged trie (:

so does entries matter and only entries when adding a list to rethinkdns? (not including the format of the list)

**Comment by ignoramous** [comment]
*Mostly*, the content of the list being wildcard or not does not affect the final size.

**Comment by GiddyGoatGaming** [comment]
> _Mostly_, the content of the list being wildcard or not does not affect the final size.

Ok I’m on the same page as you now. Il close this issue now and the only thing relating to this now is the pull request for the optimized version of small ublock filter list.
