### ISSUE TITLE
Energized gone for good?

### ISSUE THREAD

**Issue by GiddyGoatGaming** [serverless-dns/blocklists#83]
So it seems energized.pro is just showing a blank page now the domain files are like what the host files were doing. Should we find replacements to slot into where the energized lists were? Additionally, replace the newly added energized adult lite😭

**Comment by ignoramous** [comment]
I believe the last time they went down (18 months or so ago), it was due to mounting bandwidth costs. Not sure if what's up this time around.

**Comment by ignoramous** [comment]
https://github.com/EnergizedProtection/block/issues/980

**Comment by ignoramous** [comment]
Energized is done. Down for 3 weeks now. Sigh.

**Comment by ignoramous** [comment]
All except 2 Energized lists have been replaced: #118
