### ISSUE TITLE
Introduce "type" field to mark wildcard lists

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/blocklists#9]
Some lists are already implicitly treated as wildcarded ([resolver](https://github.com/serverless-dns/blocklist-wrapper/blob/7f932b1f9748412b1eede9d0d2d645bee98b449e/blocklistWrapper.js#L279), [app](https://github.com/celzero/gotrie/blob/d9d0dcea9cbdb7738628cea0668c5fb99b959a9d/trie/frozentrie.go#L15)); make that explicit in the `json` file.

```
"type": "wildcard",
```
Make the field optional.

**Comment by ignoramous** [comment]
Interesting suggestion from badmojr... treat _all_ lists as wildcards.

**Comment by Horizonbli** [comment]
Sorry for stepping in, but that's a great idea. Also, and I apologize if I am writing in the wrong place, but what about also having the option for regular expressions?

**Comment by ignoramous** [comment]
> what about also having the option for regular expressions?

Not enough cpu processing power to deal with those, currently. We run similar code on both on-device (battery concerns with more cpu use), on our servers on fly (cheapest instances), and on serverless environments like cloudflare (hard cap on 50milliseconds cpu time). All three places where cpu is at a premium.

**Comment by ignoramous** [comment]
All lists are wildcards: https://github.com/serverless-dns/serverless-dns/commit/cb6e02a19c3aa0b962d452d0b468eb79fb43adcf

**Comment by ignoramous** [comment]
Per above, I don't see a need to mark lists are wildcards, anymore.

**Comment by ignoramous** [comment]
Ref: https://github.com/bongochong/CombinedPrivacyBlockLists/commit/1f2aa973b2f2c1f84909015f9a916ef01f358aca

**Comment by ignoramous** [comment]
Also: https://github.com/lightswitch05/hosts/issues/301
